### ISSUE TITLE
Differential evaluation: Skip crossover step in generation 0

### ISSUE THREAD

**Issue by bangerth** [bangerth/SampleFlow#142]
Follow-up to #138: In the code as it is after #140, the differential evaluation sampler does a cross-over step in generation zero. That seems a bit silly: Nothing has evolved yet, though it is also not wrong.

@dawsoneliasen -- what do you think? Would it be worth skipping the cross-over step in generation zero? If so, want to give it a try?

**Comment by dawsoneliasen** [comment]
@bangerth Good observation, I agree that it's a bit silly. I'll add an additional criterion to the crossover conditional.

**Comment by bangerth** [comment]
OK. You'll probably have to update the test output in the process.
