### ISSUE TITLE
Questions about the spurious auto-covariance consumer

### ISSUE THREAD

**Issue by bangerth** [bangerth/SampleFlow#39]
@MantautasRimkus -- Looking through the code that implements the spurious autocovariance consumer, here are a couple of questions:

* In the formulas in the class documentation, the gamma terms are defined with a factor `1/n` times the sum that runs from 1 to `n-l`. But in the code, you use `1/(n-l)` in all places I could find. I think the latter is actually correct. Do you agree? If so, can you update the formulas in the class documentation?

* In the documentation, the last term for `gamma_n(l)` is `\frac{n-l}{n} \bar{x}_n^T \bar{x}_n`. I think this is also correct. But in the code, the update at the end of the `get()` function does not have the factor `(n-l)/n`:  https://github.com/bangerth/SampleFlow/blob/master/include/sampleflow/consumers/spurious_autocovariance.h#L297 Here, we simply add `\bar{x}_n^T \bar{x}_n`. Do you agree that there is a bug here?

**Comment by MantautasRimkus** [comment]
I see mistakes in documentation. Term (n-l)/(n-l) =1, that is why nothing done in the end of the get() function. I hope to fix the documentation today.

**Comment by bangerth** [comment]
On 11/7/19 3:40 PM, MantautasRimkus wrote:
> I see mistakes in documentation. Term (n-l)/(n-l) =1, that is why nothing done 
> in the end of the get() function. I hope to fix the documentation today.

That would be nice. Thanks!

**Comment by bangerth** [comment]
Fixed by #105.
