### ISSUE TITLE
CMake fails: Could not find a package configuration file provided by "boost_signals"

### ISSUE THREAD

**Issue by dawsoneliasen** [bangerth/SampleFlow#64]
@bangerth 
On my Manjaro Linux box, I am trying to install SampleFlow for development. Following the instructions in the README, I executed `cmake .` and got this output: 
```
CMake Error at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR signals)
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.17/Modules/FindBoost.cmake:2145 (find_package_handle_standard_args)
  CMakeLists.txt:34 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/dawson/projects/SampleFlow/CMakeFiles/CMakeOutput.log".
```
I figured I just needed to install boost, so I did that and then executed `cmake .` again. Then I got this:
```
CMake Error at /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package):
  Could not find a package configuration file provided by "boost_signals"
  (requested version 1.72.0) with any of the following names:

    boost_signalsConfig.cmake
    boost_signals-config.cmake

  Add the installation prefix of "boost_signals" to CMAKE_PREFIX_PATH or set
  "boost_signals_DIR" to a directory containing one of the above files.  If
  "boost_signals" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component)
  /usr/share/cmake-3.17/Modules/FindBoost.cmake:444 (find_package)
  CMakeLists.txt:34 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/dawson/projects/SampleFlow/CMakeFiles/CMakeOutput.log".
```
Am I doing something wrong with the installation? Are there other dependencies that need to be installed?

**Comment by bangerth** [comment]
Boost has many sub-packages that are generally installed separately. I'm not sure what the package name for the boost signals package is for your OS, but you can probably look it up. For example, this is for ubuntu: https://packages.ubuntu.com/bionic/libboost-signals-dev

If your package manager accepts wildcards, you might also be able to just install everything of the form `libboost-*`.

**Comment by dawsoneliasen** [comment]
Took a look, and the boost libraries (`boost-libs` on pacman) were automatically installed with boost. I noticed that I had something called "signals2", not "signals". After some searching, I learned that signals was deprecated in boost 1.59, and removed in boost 1.69. I tried changing the `REQUIRED COMPONENTS` in CMakeLists.txt to require signals2 instead of signals, but I got the same error (except "signals" was replaced by "signals2" in the error message). Some more searching and I found [this PR](https://github.com/ros/geometry2/pull/354), where the author points out that signals2 should not be included in the `REQUIRED COMPONENTS` since it is a header-only library (signals is not). I replicated the change made in that PR, and `cmake .` succeeded. 

It seems that this issue is caused by my version of boost (1.72) being newer than yours. What version do you have? I'm guessing it is <1.69. I could try uninstalling boost 1.72 and installing the same version that you have. Or maybe it would be preferable to upgrade the dependency to boost 1.72 to avoid this problem in the future? If granted push access I could push a branch with the change that I made for you to take a look at.
